<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UploadHandler'                        => __DIR__ . '/public/assets/cms-jquery/plugins/file-upload/server/php/UploadHandler.php',
    'CmsJquery\Controller\AdminController' => __DIR__ . '/src/Controller/AdminController.php',
    'CmsJquery\Module'                     => __DIR__ . '/src/Module.php',
    'CmsJqueryTest\Framework\TestCase'     => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsJqueryTest\SampleTest'             => __DIR__ . '/tests/SampleTest.php',
);
