<?php
/**
 * CoolMS2 JQuery module (http://www.coolms.com/)
 * 
 * @link      http://github.com/coolms/CmsJquery for the canonical source repository
 * @copyright Copyright (c) 2006-2014 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsJquery;

$this->headLink()->prependStylesheet($this->basePath('assets/cms-jquery/ui/jquery-ui.theme.min.css'))
                 ->prependStylesheet($this->basePath('assets/cms-jquery/ui/jquery-ui.min.css'));

$this->headScript()
     ->prependFile($this->basePath('assets/cms-jquery/ui/jquery-ui.min.js'))
     ->prependFile($this->basePath('assets/cms-jquery/jquery.min.js'));
     //->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js');
